services:
  postgres:
    container_name: SeMa-database
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD

  adminer:
    container_name: SeMa-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sema-api
    container_name: SeMa-api
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET=${SECRET}
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      #- ./node_modules:/app/node_modules
    depends_on:
      - postgres

